### ISSUE TITLE
Entrega del TFG

### ISSUE THREAD

**Issue by davidelinformatico** [davidelinformatico/TFG#56]

**Comment by alvarag** [comment]
Algunos comentarios finales sobre la memoria y anexos.

Importante, se ha quedado una llave abierta en algún \texttt{} y hace que todo el manual de usuario esté con la fuente que no debería. Revisa bien esto antes de la versión final.

[memoriaAAG.pdf](https://github.com/davidelinformatico/TFG/files/5829128/memoriaAAG.pdf)
[anexosAAG.pdf](https://github.com/davidelinformatico/TFG/files/5829129/anexosAAG.pdf)
